# Documentation
task:
  id:  "id of the task"
  type: "fix-error, summarise, generate-file"
  category: "excel, pdf"
  description:
    "Description of task for human use."

input:
  original-input-file: "name of original input file"
  notes:
    "Notes for human use."

# --------------------------------
# Config (parsed by eval pipeline, changes in this section will impact eval pipeline)
# --------------------------------
evaluation:
  type: "programmatic, llm"
