# Documentation
task:
  id: e-003
  type: extraction
  category: web
  description:
    "LLM is asked to obtain AMZN's fiscal year 2024 10K from either Edgar or IR website. Then, it is asked to extract the next 24 months unconditional purchase obligations from 31 Dec 2024. The answer is USD16,477m (USD8,536m + USD7,941m)"

input:
  input-file-original: None
  input-file-used: None
  notes: None
