# Documentation
task:
  id: e-001
  type: fix-error
  category: excel
  description:
    "LLM is provided a simple LBO model with an unbalanced balance sheet. LLM
    needs to find the source of the error. In this case, formula in row 140
    neglects to add values in row 138."

input:
  input-file-original: "ib-bench/data-factory/human-generated/dave-and-busters.xlsx"
  input-file-used: "input-file-original broken in row 140"
  notes:
    "LLM is provided a guide on how to fix an unbalanced balance sheet. We also
    specify that there is only 1 source of error"
