# Documentation
task:
  id: m-001
  type: summarise
  category: pdf
  description: "LLM is asked to create a Pubic Information Book (PIB) which has last 3 years 10K's and 10Q's, last Investor Presentation and any publicly available equity research reports. It is then asked to create a 1-page summary."

input:
  original-input-file: #TODO
  notes: "LLM provided with 3 equity research reports as they would not have access to broker reports."

# --------------------------------
# Config (parsed by eval pipeline, changes in this section will impact eval pipeline)
# --------------------------------
evaluation:
  type: llm
